// <auto-generated />
namespace MarkomPos.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Add_enum_ProductGroupTypeEnum : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_enum_ProductGroupTypeEnum));
        
        string IMigrationMetadata.Id
        {
            get { return "202106030304307_Add_enum_ProductGroupTypeEnum"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
